version: '3'
services:
  server:
    image: gealber/construct_demo:latest
    restart: "unless-stopped"
    ports:
      - "3000:3000"
    environment:
      PRIVATE_KEY_PATH: /app/serializer/jwt/key_backup/id_rsa
      PUBLIC_KEY_PATH: /app/serializer/jwt/key_backup/id_rsa.pub
      MONGO_URL: mongodb://mongodb:27017/db
      REDIS_URL: redis://redis:6379/0
  mongodb:
    image: mongo:4.2.1-bionic
    ports:
      - "27017:27017"
    restart: always
  redis:
    image: redis:6.0-alpine3.11
    restart: always
    ports:
      - "6379:6379"

