FROM golang:1.13.3-alpine as builder

RUN apk add --no-cache git
ARG DOCKER_GIT_CREDENTIALS
RUN git config --global credential.helper store && echo "${DOCKER_GIT_CREDENTIALS}" > ~/.git-credentials

WORKDIR $HOME/app/construct_demo

ENV GOPROXY "direct"
ENV GOSUMDB "off"
COPY go.mod go.mod
RUN go mod download

COPY ./ ./
RUN go build -o $GOPATH/bin/server ./

# new stage
FROM alpine:latest

LABEL maintainer="Gealber Morales Basalo <gealbermorales@gmail.com>"

WORKDIR /root/

COPY --from=builder /go/bin/server .

CMD ["./server"]
